# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4eeb8f5d562df7047476bd288d0d6cb8"
name = "Farm to Home Add Extras"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_proxy]
url = "https://p01--recharge-add-extras--yj8tfgj8dpk9.code.run"
subpath = "add-extras"
prefix = "apps"
